import {StyleSheet} from 'react-native'

export const styles = StyleSheet.create({
    container:{
        height:80,
        marginTop:16,
        borderBottomColor:"#737373",
        borderBottomWidth:1
    },
    date:{
        backgroundColor:"#1E63CB",
        height:20,
        alignItems:"flex-start"
    },
    textDate:{
        color:"white", 
        paddingHorizontal:10
    },
    details:{
        display:"flex",
        marginLeft:10,
        flexDirection:'row',
        flexWrap:"wrap",
        alignItems:"center",
        paddingTop:5,
        paddingBottom:10
    },
    icon:{
        justifyContent:'center',
        color:'#FFFFFF',
        backgroundColor:'#1E63CB',
        fontSize:40,
        alignItems:"center",
        marginRight:10
    },
    presupuestoName:{
        fontSize:16,
        fontWeight:"bold"
    }
})