import {StyleSheet} from 'react-native'

export const styles=StyleSheet.create({
    mainContainer:{
        flex:1,
        backgroundColor:"gray"
    },
    iconView:{
        flex:1,
        justifyContent:'center',
        alignContent:'center',
        backgroundColor:'#1E63CB',
        alignItems:'center',
        backgroundColor:'#1E63CB',
    },
    icon:{
        color:'#ffffff',
        fontSize:120,
    },
    title:{
        color:'black',
        fontWeight:'bold',
        fontSize:20,
        textTransform:'uppercase',
        marginBottom:10
    },
    form:{
        flex:2,
        backgroundColor:"#ffffff",
        flexDirection:'column',
        borderRadius:5,
        padding:16
    },
    txtInput:{
        borderWidth:2,
        borderColor:'#1E63CB',
        fontSize:16,
        paddingHorizontal:16,
        borderRadius:16
    },
    label:{
        fontSize:16
    },
    forgot:{
        marginTop:16,
        alignItems:'center',
        justifyContent:'center',
    },
    btn:{
        marginTop:16,
        padding:16,
        borderRadius:20,
        backgroundColor:'#1E63CB',
        alignItems:'center',
    },
    signUp:{
        display:"flex",
        flexDirection:"row",
        justifyContent:'center',
        backgroundColor:'#ffffff'
    }
})